### ISSUE TITLE
Could releases be git tagged?

### ISSUE THREAD

**Issue by natoscott** [RedisLabs/rmtest#6]
Hi there,

It would be helpful for distribution packagers if the release numbers used in setup.py could also be reflected in git tags (currently rmtest has no git tags but is on release 0.6.6 in pypi).

This would allow the use of source tarballs from github rather than pypi - the latter lacks files like README.md and LICENSE which are needed in various distributions.

cheers.

**Comment by dvirsky** [comment]
No problem, but will it help if I add them to the pypi package?

**Comment by natoscott** [comment]
@dvirsky either/both is fine by me.  Thanks!

**Comment by dvirsky** [comment]
@natoscott I've tagged a release, I'll try add the files to the package in the next version. https://github.com/RedisLabs/rmtest/releases/tag/v0.6.6
