### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by natoscott** [RedisLabs/rmtest#8]
I'm seeing failures in Fedora rebloom & rejson module package builds stemming from the issue underlying commit 7608a20d ... any chance a new rmtest release could be tagged and set free?

That commit updates the setup.py version to 0.6.7 but there's no tag here on github.  It'd make my day if a new rmtest-0.6.8 could be rolled out with the python3 support as well ... 8^)

cheers.

**Comment by dvirsky** [comment]
yeah sure I'll merge the latest changes and release it

**Comment by natoscott** [comment]
@dvirsky any issues with those changes, and/or anything else I can do to help out there?  cheers.

**Comment by natoscott** [comment]
@dvirsky got any time to spin that release out soon?  TIA.

**Comment by itamarhaber** [comment]
Hello @natoscott,

Regrettably, @dvirsky is no longer involved in this project and will probably not be able to release the latest and greatest. I gave it a shot in his stead and released https://github.com/RedisLabs/rmtest/releases/tag/v0.6.9 here and on pypi.

Crossing fingers nothing breaks horribly,
Itamar
